services:

  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    commands:
      init:
        - set -x
        - apt-get update
        - apt-get install -y libzip-dev mysql-client
        - pecl install zip
        - docker-php-ext-enable zip
        - mkdir "${TUGBOAT_ROOT}/web"
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
      
      update:
        - composer create-project craftcms/craft $DOCROOT
        - ${DOCROOT}/craft setup/security-key
        - ${DOCROOT}/craft setup/db-creds --interactive=0 --database=tugboat --user=tugboat --password=tugboat --server=mysql
 
  mysql:
    image: tugboatqa/mysql:5
    commands:
      init: 
      - set -x
      
