services:

  php:
    image: tugboatqa/php:7-apache
    default: true
    depends: mysql
    commands:
      init:
        - set -x
        - apt-get update
        - apt-get install libzip-dev
        - pecl install zip
        - docker-php-ext-enable zip
        - mkdir "${TUGBOAT_ROOT}/web"
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
      
      update:
        - composer create-project craftcms/craft $DOCROOT
 
  mysql:
    image: tugboatqa/mysql:5.5
    commands:
      init: 
      - set -x
      - 'Running init within MySQL Service'
      
